Added legacy costs calculation
Rise-Vision/bigquery-queries pull request #182
Opened 2021-04-08 22:22 UTC by alexey-rise

Please remember apply the changes on Big Query UI

2021-04-13 16:31 UTC, tejohnso requested changes

2021-04-13 16:31 UTC, tejohnso commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +endpointDownloads_legacy1 as
Instead of "legacy" 1 through 7 could you name these more precisely?

2021-04-13 16:31 UTC, tejohnso commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +REGEXP_EXTRACT(URLDECODE(REGEXP_EXTRACT(cs_uri, r'parent=([^?&#]*)')), r'id=([^?&#]*)') as endpointId,
> r'id=([^?&#]*)' as endpointId

Wouldn't `r'id=([^&]*)'` work?

2021-04-13 16:31 UTC, tejohnso commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +(strpos(URLDECODE(cs_uri), '://widgets.risevision.com/viewer') > 0 or strpos(URLDECODE(cs_uri), '://viewer.risevision.com') > 0)
This endpointType is Display but I think it's going to capture shared schedules as well.  EG: `https://widgets.risevision.com/viewer/?type=sharedschedule&id=...`

Maybe it's intentional. I'll wait for the more precise "legacyX" naming before continuing.

2021-04-13 18:54 UTC, alexey-rise commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +endpointDownloads_legacy1 as
@tejohnso fixed.

2021-04-13 18:54 UTC, alexey-rise commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +(strpos(URLDECODE(cs_uri), '://widgets.risevision.com/viewer') > 0 or strpos(URLDECODE(cs_uri), '://viewer.risevision.com') > 0)
@tejohnso good catch, fixed.

2021-04-13 18:59 UTC, alexey-rise commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +REGEXP_EXTRACT(URLDECODE(REGEXP_EXTRACT(cs_uri, r'parent=([^?&#]*)')), r'id=([^?&#]*)') as endpointId,
@tejohnso it probably would, but since # can be present in a URL I use `r'param_name=([^?&#]*)'` for all query param extraction and I see no reason to tailor the expression for each specific case.

2021-04-14 14:50 UTC, alexey-rise commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +where _TABLE_SUFFIX = FORMAT_DATE("%Y%m%d",DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) and strpos(URLDECODE(cs_uri), 'ype=sharedschedule') > 0 and strpos(URLDECODE(cs_uri), '://widgets.risevision.com/v
@tejohnso I revised the query to clarify the `endpointType` mapping in the last commit, please review and let me know if you still need a spreadsheet.

2021-04-14 15:09 UTC, tejohnso commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +where _TABLE_SUFFIX = FORMAT_DATE("%Y%m%d",DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) and strpos(URLDECODE(cs_uri), 'ype=sharedschedule') > 0 and strpos(URLDECODE(cs_uri), '://widgets.risevision.com/v
Doesn't have to be a spreadsheet but I think we need something, maybe a doc, clarifying how these costs are calculated. For transparency, and also as a reference and a discussion area related to cost calculations.

2021-04-14 16:50 UTC, alexey-rise commented on projects/endpoint-event-logs/datasets/logs/dailyCostSummary.sql
> +where _TABLE_SUFFIX = FORMAT_DATE("%Y%m%d",DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY)) and strpos(URLDECODE(cs_uri), 'ype=sharedschedule') > 0 and strpos(URLDECODE(cs_uri), '://widgets.risevision.com/v
@tejohnso please review and let me know if [this ](https://docs.google.com/document/d/1i5E5VGaybBVLTSZ3wiTXG04Zhw8ENhdG2QDNLQXDTRo/edit?usp=sharing)is acceptable.

2021-04-14 17:13 UTC, tejohnso approved these changes
Looks good, thanks

2021-04-14 17:19 UTC, merged